apiVersion: batch/v1
kind: Job
metadata:
  name: failure-job
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: failure-job
        image: busybox
        command: ["echo 'Running Job'; sleep 5; exit 1"]
      restartPolicy: OnFailure
