apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-web-to-nginx
spec:
  replicas: 3
  selector:
    app: k8s-web-to-nginx
  template:
    metadata:
      name: k8s-web-to-nginx
      labels:
        app: k8s-web-to-nginx
    spec:
      containers:
        - name: k8s-web-to-nginx
          image: kulerock/k8s-web-hello
          ports:
            - containerPort: 3000
